language: php

php:
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.2
      env: SYMFONY_VERSION='^4.0'
    - php: 7.3
      env: SYMFONY_VERSION='^4.0'
    - php: 7.3
      env: DEPENDENCIES=beta

before_install:
  - composer self-update
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev symfony/framework-bundle:${SYMFONY_VERSION} --no-update; fi

install: composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit
